# Destinations are processed in first-matching order.
# A route can match only one destination.
# hasPath and hasHeader are treated as AND conditions, and should be listed in more specific->less specific order.

destinations:
  # destination_name:
  #   url: (optional) used when gateway should completely override the request domain,
  #        such as when pointing to a cloud function.
  #   hostname: (mandatory without url) hostname override to forward the incoming request to.
  #   scheme: (mandatory with hostname) scheme of the override hostname.
  #   hasPath: array of path tokens used to match a destination
  #   hasHeader: array of header key:value pairs used to match a destination

  prod_v3_micro1:
    url: null
    hostname: webhook.site/43435bce-efd5-4520-9674-7911102e4dae
    scheme: https
    hasPath: [ 'v3', 'one' ]
    hasHeader: [ ]

  prod_v3_micro2:
    url: null
    hostname: webhook.site/43435bce-efd5-4520-9674-7911102e4dae
    scheme: https
    hasPath: [ 'v3', 'two' ]
    hasHeader: [ ]

  prod_v3_micro3:
    url: null
    hostname: webhook.site/43435bce-efd5-4520-9674-7911102e4dae
    scheme: https
    hasPath: [ 'v3', 'three' ]
    hasHeader: [ ]

  staging_v3_core:
    url: null
    hostname: webhook.site/43435bce-efd5-4520-9674-7911102e4dae
    scheme: https
    hasPath: [ 'v3' ]
    hasHeader: [ 'env:staging' ]

  prod_v3_core:
    url: null
    hostname: webhook.site/43435bce-efd5-4520-9674-7911102e4dae
    scheme: https
    hasPath: [ 'v3' ]
    hasHeader: [ ]
